spring:
  datasource:
    mapper-location: classpath:/mapper/**/*.xml
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true