spring:
  datasource:
#    mapper-location: classpath:/mapper/**/*.xml
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  upload:
    path: src/main/resources/upload/profile/

#  sql:
#    init:
#      mode: always
#
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    jdbc-type-for-null: null
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true