INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME)
VALUES ('admin@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'admin');
INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME)
VALUES ('user01@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'user01');
INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME)
VALUES ('user02@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'user02');