INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME, ROLE)
VALUES ('admin@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'admin', 'ROLE_ADMIN');
INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME, ROLE)
VALUES ('user01@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'user01', 'ROLE_USER');
INSERT INTO MEMBER (EMAIL, MEMBER_PWD, MEMBER_NAME, ROLE)
VALUES ('user02@gmail.com', '$2a$10$MRbUZnXLRwLUQUS0UJVemuX7Gf9oNTz7qAbSgbCVNDJxIv2xo8nhq', 'user02',  'ROLE_USER');